trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'vuejs-app'
  variables:
  dockerRegistryServiceConnection: 'VuejsContainer'
  imageRepository: 'vue-app'
  containerRegistry: 'VuejsContainer'
  tag: '$(Build.BuildId)'
  azureServiceConnection: 'VuejsDemoDocker'
  appServiceName: 'VuejsDemoDocker'

steps:
# Step 1: Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)

# Step 2: Deploy Docker Image to Azure App Service
- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(appServiceName)'
    containers: |
      $(containerRegistry)/$(imageName):$(tag)