trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'vuejs-docker-app'
  dockerRegistryServiceConnection: 'VuejsDockerContainerV2'
  containerRegistry: 'VuejsDockerContainerV2'
  tag: '$(Build.BuildId)'

  acrName: 'VuejsDockerContainerV2'                                 # Azure Container Registry name
  resourceGroup: 'VuejsDockerDemoV2'                                # Azure Resource Group
  containerGroup: 'vuejs-docker-demo-container-instance'            # ACI Container Group name
  region: 'Canada Central'                                          # Azure region (e.g., eastus)
  azureSubscription: 'VuejsDockerDemoResourcesServiceConnection'    # Azure resources group service connection


steps:

# Step 1: Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)

# Step 2: Deploy to Azure Container Instances
- task: AzureCLI@2
  displayName: 'Deploy to Azure Container Instances'
  inputs:
    azureSubscription: '$(azureSubscription)'  # Azure RM connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      # Get ACR credentials
      ACR_USERNAME=$(az acr credential show --name $(acrName) --query "username" --output tsv)
      ACR_PASSWORD=$(az acr credential show --name $(acrName) --query "passwords[0].value" --output tsv)

      # # Delete the existing container group if it exists
      # az container delete \
      # --name $(containerGroup) \
      # --resource-group $(resourceGroup) \
      # --yes || echo "No existing container group to delete."

      # # Deploy the container
      # az container create \
      #   --resource-group $(resourceGroup) \
      #   --name $(containerGroup) \
      #   --image $(acrName).azurecr.io/$(imageName):$(tag) \
      #   --registry-login-server $(acrName).azurecr.io \
      #   --registry-username $ACR_USERNAME \
      #   --registry-password $ACR_PASSWORD \
      #   --dns-name-label $(containerGroup) \
      #   --ports 80 \
      #   --restart-policy Always

      # # Check if the container group exists
      # if az container show --name $(containerGroup) --resource-group $(resourceGroup) &> /dev/null; then
      #   echo "Container group exists. Updating the image..."
      #   az container update \
      #     --name $(containerGroup) \
      #     --resource-group $(resourceGroup) \
      #     --image $(acrName).azurecr.io/$(imageName):$(tag)
      # else
      #   echo "Container group does not exist. Creating a new one..."
      #   az container create \
      #     --resource-group $(resourceGroup) \
      #     --name $(containerGroup) \
      #     --image $(acrName).azurecr.io/$(imageName):$(tag) \
      #     --registry-login-server $(acrName).azurecr.io \
      #     --registry-username $ACR_USERNAME \
      #     --registry-password $ACR_PASSWORD \
      #     --dns-name-label $(dnsName) \
      #     --ports 80 \
      #     --location $(region) \
      #     --restart-policy Always
      # fi

      az container update \
      --name $(containerGroup) \
      --resource-group $(resourceGroup) \
      --image $(acrName).azurecr.io/$(imageName):$(tag)
