trigger:
  branches:
    include:
      - master  # Trigger pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build

variables:
  azureContainerRegistry: 'VuejsContainer'  # Azure Container Registry name
  imageName: 'vuejs-app'  # Name of your Docker image
  appServiceName: 'VuejsDemoDocker'
  azureSubscription: 'VuejsDemoDocker'

steps:
# 1. Checkout the code
- task: Checkout@1
  displayName: 'Checkout Code'

# 2. Set up Docker
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(azureContainerRegistry)'  # Use your ACR
    repository: '$(azureContainerRegistry)/$(imageName)'
    dockerfile: '**/Dockerfile'  # Path to the Dockerfile
    buildContext: '.'
    tags: |
      latest

# 3. Deploy to Azure App Service using Docker container
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appServiceName)'  # Name of the App Service
    containerRegistry: '$(azureContainerRegistry)'
    imageName: '$(azureContainerRegistry)/$(imageName):latest'
    isPushEnabled: true