trigger:
  branches:
    include:
      - master  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true
  imageName: 'vuejs-app'
  azureContainerRegistry: '73f1a52b-6568-4826-8fd3-62b9979d184f'  # Replace with the actual service connection name
  azureSubscription: 'c057640d-737a-49c1-91b1-f4a4ac5f8ab6'       # Replace with the actual Azure service connection name
  azureResourceGroup: 'VuejsDemoDocker_group'
  appName: 'VuejsDemoDocker'

jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image to ACR'
    steps:
      - task: Checkout@1
        displayName: 'Checkout code'

      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: $(azureContainerRegistry)
          repository: $(imageName)
          command: 'buildAndPush'
          Dockerfile: $(Build.SourcesDirectory)/Dockerfile
          tags: latest  # Use Build ID as the tag

  - job: DeployToAzure
    displayName: 'Deploy Docker Image to Azure App Service'
    dependsOn: BuildAndPush
    steps:
      - task: AzureCLI@2
        displayName: 'Azure CLI - Deploy Docker Image'
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az webapp config container set \
              --name $(appName) \
              --resource-group $(azureResourceGroup) \
              --docker-custom-image-name $(azureContainerRegistry)/$(imageName):latest
