trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'VuejsContainer'
  imageRepository: 'vue-app'
  containerRegistry: 'vuejscontainer.azurecr.io'
  tag: '$(Build.BuildId)'
  azureServiceConnection: 'VuejsDemoDocker'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Checkout@1

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure App Service
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: 'VuejsDemo'
              containerRegistry: $(containerRegistry)
              imageName: $(imageRepository)
              tag: $(tag)